//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrutusService.JavaEndpoint {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.exia.com/", ConfigurationName="JavaEndpoint.ProjectEndpoint")]
    public interface ProjectEndpoint {
        
        // CODEGEN: Generating message contract since element name decryptedMessage from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.exia.com/ProjectEndpoint/queueOperationRequest", ReplyAction="http://facade.exia.com/ProjectEndpoint/queueOperationResponse")]
        BrutusService.JavaEndpoint.queueOperationResponse queueOperation(BrutusService.JavaEndpoint.queueOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.exia.com/ProjectEndpoint/queueOperationRequest", ReplyAction="http://facade.exia.com/ProjectEndpoint/queueOperationResponse")]
        System.Threading.Tasks.Task<BrutusService.JavaEndpoint.queueOperationResponse> queueOperationAsync(BrutusService.JavaEndpoint.queueOperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queueOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queueOperation", Namespace="http://facade.exia.com/", Order=0)]
        public BrutusService.JavaEndpoint.queueOperationRequestBody Body;
        
        public queueOperationRequest() {
        }
        
        public queueOperationRequest(BrutusService.JavaEndpoint.queueOperationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class queueOperationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string decryptedMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int token;
        
        public queueOperationRequestBody() {
        }
        
        public queueOperationRequestBody(string decryptedMessage, string key, string filename, int token) {
            this.decryptedMessage = decryptedMessage;
            this.key = key;
            this.filename = filename;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queueOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queueOperationResponse", Namespace="http://facade.exia.com/", Order=0)]
        public BrutusService.JavaEndpoint.queueOperationResponseBody Body;
        
        public queueOperationResponse() {
        }
        
        public queueOperationResponse(BrutusService.JavaEndpoint.queueOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class queueOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addedToQueue;
        
        public queueOperationResponseBody() {
        }
        
        public queueOperationResponseBody(bool addedToQueue) {
            this.addedToQueue = addedToQueue;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProjectEndpointChannel : BrutusService.JavaEndpoint.ProjectEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectEndpointClient : System.ServiceModel.ClientBase<BrutusService.JavaEndpoint.ProjectEndpoint>, BrutusService.JavaEndpoint.ProjectEndpoint {
        
        public ProjectEndpointClient() {
        }
        
        public ProjectEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BrutusService.JavaEndpoint.queueOperationResponse BrutusService.JavaEndpoint.ProjectEndpoint.queueOperation(BrutusService.JavaEndpoint.queueOperationRequest request) {
            return base.Channel.queueOperation(request);
        }
        
        public bool queueOperation(string decryptedMessage, string key, string filename, int token) {
            BrutusService.JavaEndpoint.queueOperationRequest inValue = new BrutusService.JavaEndpoint.queueOperationRequest();
            inValue.Body = new BrutusService.JavaEndpoint.queueOperationRequestBody();
            inValue.Body.decryptedMessage = decryptedMessage;
            inValue.Body.key = key;
            inValue.Body.filename = filename;
            inValue.Body.token = token;
            BrutusService.JavaEndpoint.queueOperationResponse retVal = ((BrutusService.JavaEndpoint.ProjectEndpoint)(this)).queueOperation(inValue);
            return retVal.Body.addedToQueue;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BrutusService.JavaEndpoint.queueOperationResponse> BrutusService.JavaEndpoint.ProjectEndpoint.queueOperationAsync(BrutusService.JavaEndpoint.queueOperationRequest request) {
            return base.Channel.queueOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<BrutusService.JavaEndpoint.queueOperationResponse> queueOperationAsync(string decryptedMessage, string key, string filename, int token) {
            BrutusService.JavaEndpoint.queueOperationRequest inValue = new BrutusService.JavaEndpoint.queueOperationRequest();
            inValue.Body = new BrutusService.JavaEndpoint.queueOperationRequestBody();
            inValue.Body.decryptedMessage = decryptedMessage;
            inValue.Body.key = key;
            inValue.Body.filename = filename;
            inValue.Body.token = token;
            return ((BrutusService.JavaEndpoint.ProjectEndpoint)(this)).queueOperationAsync(inValue);
        }
    }
}
