//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dechifr_client.BrutusControl {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrutusControl.IBrutusControl")]
    public interface IBrutusControl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrutusControl/startBrutus", ReplyAction="http://tempuri.org/IBrutusControl/startBrutusResponse")]
        void startBrutus(string encrypted_Message, string filename, string taskId, System.Threading.CancellationTokenSource t_cancel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrutusControl/startBrutus", ReplyAction="http://tempuri.org/IBrutusControl/startBrutusResponse")]
        System.Threading.Tasks.Task startBrutusAsync(string encrypted_Message, string filename, string taskId, System.Threading.CancellationTokenSource t_cancel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrutusControl/stopBrutus", ReplyAction="http://tempuri.org/IBrutusControl/stopBrutusResponse")]
        bool stopBrutus(int task_ID, string fileName, string final_message, string key, string email, double fiability);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrutusControl/stopBrutus", ReplyAction="http://tempuri.org/IBrutusControl/stopBrutusResponse")]
        System.Threading.Tasks.Task<bool> stopBrutusAsync(int task_ID, string fileName, string final_message, string key, string email, double fiability);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrutusControl/killBrutus", ReplyAction="http://tempuri.org/IBrutusControl/killBrutusResponse")]
        void killBrutus(int task_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrutusControl/killBrutus", ReplyAction="http://tempuri.org/IBrutusControl/killBrutusResponse")]
        System.Threading.Tasks.Task killBrutusAsync(int task_ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrutusControlChannel : dechifr_client.BrutusControl.IBrutusControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrutusControlClient : System.ServiceModel.ClientBase<dechifr_client.BrutusControl.IBrutusControl>, dechifr_client.BrutusControl.IBrutusControl {
        
        public BrutusControlClient() {
        }
        
        public BrutusControlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrutusControlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrutusControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrutusControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void startBrutus(string encrypted_Message, string filename, string taskId, System.Threading.CancellationTokenSource t_cancel) {
            base.Channel.startBrutus(encrypted_Message, filename, taskId, t_cancel);
        }
        
        public System.Threading.Tasks.Task startBrutusAsync(string encrypted_Message, string filename, string taskId, System.Threading.CancellationTokenSource t_cancel) {
            return base.Channel.startBrutusAsync(encrypted_Message, filename, taskId, t_cancel);
        }
        
        public bool stopBrutus(int task_ID, string fileName, string final_message, string key, string email, double fiability) {
            return base.Channel.stopBrutus(task_ID, fileName, final_message, key, email, fiability);
        }
        
        public System.Threading.Tasks.Task<bool> stopBrutusAsync(int task_ID, string fileName, string final_message, string key, string email, double fiability) {
            return base.Channel.stopBrutusAsync(task_ID, fileName, final_message, key, email, fiability);
        }
        
        public void killBrutus(int task_ID) {
            base.Channel.killBrutus(task_ID);
        }
        
        public System.Threading.Tasks.Task killBrutusAsync(int task_ID) {
            return base.Channel.killBrutusAsync(task_ID);
        }
    }
}
